pipelines:
  default:
    - step:
        name: Build Jekyll Site
        image: ruby:3.2
        script:
          - gem install bundler jekyll
          - bundle install
          - jekyll build
    - step:
        name: Deploy to Bitbucket Pages
        script:
          - pipe: atlassian/bitbucket-pages-deploy:0.3.3
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              BITBUCKET_REPO_SLUG: $BITBUCKET_REPO_SLUG
